server:
  port: 8888
spring:
  application:
    name: server-config-center
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/config-repo
          searchPaths: '{application}'  #搜索各个以服务名命名的文件夹下的所有yml
eureka:
  instance:
    hostname: localhost
    instance-id: localhost:8888
  client:
    registerWithEureka: false  #是否将eureka自身作为应用注册到eureka注册中心
    fetchRegistry: false       #为true时，可以启动，但报异常：Cannot execute request on any known server
    serviceUrl:
      defaultZone: http://127.0.0.1:8888/eureka/  #注册中心地址