server:
  port: 8889
spring:
  application:
    name: feign-hystrix-1
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.16.211:8888/eureka/
  instance:
    hostname:feign-hystrix-1
ribbon:
  eureka:
    enabled: true
feign:
   hystrix:
     enabled: true
    