server:
  port: 8889
spring:
  application:
    name: feign-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname:feign
ribbon:
  eureka:
    enabled: true
feign:
   hystrix:
     enabled: true
    