server:
  port: 7777
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iechenyb/springcloud.git
          searchPaths: my-sample-config
          username: iechenyb
          password: chen13559469
  bus:
    trace:
      enabled: false
  application:
    name:config-server