server:
  port: 7777
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iechenyb/springcloud.git
          searchPaths: config-repo
          username: iechenyb
          password: 
  bus:
    trace:
      enabled: false
  application:
    name:config-server