server:
  port: 8890
spring:
  application:
    name: feign-hystrix-2
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.16.211:8888/eureka/
  instance:
    hostname:${spring.cloud.client.ipAddress}
    id:${spring.cloud.client.ipAddress}:${server.port}
ribbon:
  eureka:
    enabled: true
feign:
   hystrix:
     enabled: true
    